# Generated by Django 5.2.6 on 2025-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
