# Generated by Django 5.2.6 on 2025-09-16 08:04

import skvapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skvapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerslider',
            name='description',
            field=models.TextField(default='This is a SKV banner slider'),
        ),
        migrations.AlterField(
            model_name='bannerslider',
            name='title',
            field=models.CharField(default=skvapp.models.banner_slider_title, help_text='This is a unique title for the banner slider', max_length=255),
        ),
    ]
