# Generated by Django 5.2.6 on 2025-09-16 08:23

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skvapp', '0002_alter_bannerslider_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKVEventDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(upload_to='skv_event_detail/')),
                ('event_initial_date', models.DateTimeField()),
                ('event_final_date', models.DateTimeField()),
                ('event_location', models.CharField(max_length=255)),
                ('event_organizer', models.CharField(max_length=255)),
                ('event_contact', models.CharField(max_length=255)),
                ('event_email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'SKV Event Detail',
                'verbose_name_plural': 'SKV Event Details',
                'db_table': 'skv_event_detail',
                'ordering': ['-created_at'],
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
