# Generated by Django 5.2.6 on 2025-09-16 09:21

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skvapp', '0003_skveventdetail'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SKVNewsDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('body', django_ckeditor_5.fields.CKEditor5Field()),
                ('image', models.ImageField(upload_to='skv_news_detail/')),
                ('is_active', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skv_news_detail_author', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SKV News Detail',
                'verbose_name_plural': 'SKV News Details',
                'db_table': 'skv_news_detail',
                'ordering': ['-created_at'],
                'unique_together': {('title', 'slug')},
            },
        ),
    ]
