# Generated by Django 5.2.6 on 2025-09-16 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skvapp', '0004_skvnewsdetail'),
    ]

    operations = [
        migrations.CreateModel(
            name='SKVHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='This is a SKV history')),
                ('year', models.IntegerField(default=0, help_text='Enter the year of the history')),
                ('image', models.ImageField(upload_to='skv_history/')),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'SKV History',
                'verbose_name_plural': 'SKV Histories',
                'db_table': 'skv_history',
                'ordering': ['-order'],
                'unique_together': {('title', 'year')},
            },
        ),
    ]
