# Generated by Django 5.2.6 on 2025-09-16 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skvapp', '0005_skvhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='skveventdetail',
            name='event_location_link',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
